# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-06 23:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['category']},
        ),
    ]
